/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project__i.tuan34.tuan1;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

import project__i.tuan29.Bai_3;

/**
 *
 * @author Admin
 */
public class Bai3 extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    Bai_3 bai_3 = new Bai_3();

    public Bai3() {
        initComponents();
        setUp();
        jButton1.addActionListener((e) -> {
            jPanel2.removeAll();
        handle();
        jPanel2.updateUI();
        });
        
    }
        
    public void setUp() {
        jLabel1.setText("vị trí bắt đầu");
        jTextField1.setText("1000");
        jLabel2.setText("vị trí kết thúc");
        jTextField2.setText("2000");
        jButton1.setText("OK");
        jPanel2.removeAll();
        jPanel2.updateUI();
    }
    
    public void handle() {
  
        int list[] = bai_3.bai_3();
        int size = list.length;
        System.out.println("size:" + size);
        int row = 10;
        int colum = 14;
        int X = 0, Y = 0;
        int WIDTH = 40, HEIGHT = 30;
        JLabel jL[][] = new JLabel[row][colum];
        int count = 0;
        jPanel2.setLayout(null);
        for (int i = 0; i < row; i++) {

            for (int j = 0; j < colum; j++) {
                jL[i][j] = new JLabel();

                jL[i][j].setText("" + list[count]);
                count++;
                jL[i][j].setHorizontalAlignment((int) CENTER_ALIGNMENT);
                jL[i][j].setBorder(new LineBorder(Color.BLACK));
                jPanel2.add(jL[i][j]);
                jL[i][j].setBounds(X, Y, WIDTH, HEIGHT);
                X = 6 * (j + 1) + (j + 1) * WIDTH;
                if (count == size) {
                    break;
                }
            }
             Y = (5 * (i + 1) + (i + 1) * HEIGHT);
           
            X = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 100, 25);

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(0, 25, 100, 25);

        jLabel2.setText("jLabel2");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 50, 100, 25);

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(0, 75, 100, 25);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 325, 100, 25);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 350);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(100, 0, 650, 350);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
