/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project__i.tuan34.tuan1;

import java.awt.Color;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import project__i.tuan29.Bai_7;

/**
 *
 * @author Admin
 */
public class Bai7 extends javax.swing.JPanel {

    /**
     * Creates new form
     */
    JPanel temp[] = new JPanel[4];

    public Bai7() {
        initComponents();
        setUp();
        jButton1.addActionListener((e) -> {

            handle();
            jPanel7.updateUI();
        });

    }

    public void setUp() {

        jLabel1.setText("Kết quả: ");
        jLabel6.setText("chia hết cho 5");
        jLabel3.setText("chia hết 5 dư 1");
        jLabel4.setText("chia hết 5 dư 2");
        jLabel5.setText("chia hết 5 dư 3");
        jButton1.setText("OK");

        temp[0] = jPanel6;
        temp[1] = jPanel3;
        temp[2] = jPanel4;
        temp[3] = jPanel5;

        temp[0].removeAll();
        temp[1].removeAll();
        temp[2].removeAll();
        temp[3].removeAll();

        temp[0].setLayout(null);
        temp[1].setLayout(null);
        temp[2].setLayout(null);
        temp[3].setLayout(null);

        temp[0].add(jLabel6);
        temp[1].add(jLabel3);
        temp[2].add(jLabel4);
        temp[3].add(jLabel5);
        jLabel6.setBounds(0, 0, 162, 25);
        jLabel3.setBounds(0, 0, 162, 25);
        jLabel4.setBounds(0, 0, 162, 25);
        jLabel5.setBounds(0, 0, 162, 25);
        jPanel7.setLayout(null);
        jPanel7.add(temp[0]);
        jPanel7.add(temp[1]);
        jPanel7.add(temp[2]);
        jPanel7.add(temp[3]);
        temp[0].setBounds(0, 0, 162, 350);
        temp[1].setBounds(162, 0, 162, 350);
        temp[2].setBounds(324, 0, 162, 350);
        temp[3].setBounds(488, 0, 163, 350);
        temp[0].updateUI();
        temp[1].updateUI();
        temp[2].updateUI();
        temp[3].updateUI();
    }

    public void handle() {

        ArrayList<ArrayList<Integer>> list = new Bai_7().bai_7();

        System.out.println("size0:" + list.get(0).size());
        System.out.println("size1:" + list.get(1).size());
        System.out.println("size2:" + list.get(2).size());
        System.out.println("size3:" + list.get(3).size());

        int row = 11;
        int colum = 2;
        int X = 0, Y = 26;
        int WIDTH = 70, HEIGHT = 20;

        int count = 0;

        JLabel jL3[][][] = new JLabel[4][row][colum];
        for (int t = 0; t < 4; t++) {

            X = 0;
            Y = 26;
            WIDTH = 70;
            HEIGHT = 20;
            row = 11;
            count = 0;
            System.out.println(temp[t].getBounds());
            if (t != 0) {
                row = 10;
            }
            for (int i = 0; i < colum; i++) {

                for (int j = 0; j < row; j++) {
                    jL3[t][j][i] = new JLabel();
                    jL3[t][j][i].setText("" + list.get(t).get(count));
                    count++;
                    jL3[t][j][i].setHorizontalAlignment((int) LEFT_ALIGNMENT);
                    jL3[t][j][i].setBorder(new LineBorder(Color.BLACK));
                    temp[t].add(jL3[t][j][i]);
                    jL3[t][j][i].setBounds(X, Y, WIDTH, HEIGHT);
                    Y = 26 + (5 * (j + 1) + (j + 1) * HEIGHT);
                    if (count == list.get(t).size()) {
                        break;
                    }

                }
                X = 10 * (i + 1) + (i + 1) * WIDTH;
                Y = 26;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 102));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 325, 100, 25);

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 100, 25);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 100, 350);

        jPanel7.setLayout(null);

        jPanel6.setLayout(null);

        jLabel6.setText("jLabel2");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 0, 162, 25);

        jPanel7.add(jPanel6);
        jPanel6.setBounds(0, 0, 162, 350);

        jPanel3.setLayout(null);

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 162, 25);

        jPanel7.add(jPanel3);
        jPanel3.setBounds(162, 0, 162, 350);

        jPanel4.setLayout(null);

        jLabel4.setText("jLabel4");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 162, 25);

        jPanel7.add(jPanel4);
        jPanel4.setBounds(324, 0, 162, 350);

        jPanel5.setLayout(null);

        jLabel5.setText("jLabel5");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 0, 162, 25);

        jPanel7.add(jPanel5);
        jPanel5.setBounds(488, 0, 163, 350);

        add(jPanel7);
        jPanel7.setBounds(100, 0, 650, 350);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
