/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_i.tuan34.tuan3;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import project_i.tuan31.Bai_5;

/**
 *
 * @author Admin
 */
public class Bai5 extends javax.swing.JPanel {

    public Bai5() {
        initComponents();
        setUp();

        jButton1.addActionListener((e) -> {
            handleJTextFiedlSetText();

        });
    }

    public void setUp() {
        jLabel2.setText("Nhập dãy N: ");
        jLabel5.setText("Kết quả: ");
        jLabel1.setText("Số nguyên tố");
        jLabel3.setText("Số hợp số ");
        jLabel2.setBorder(new LineBorder(Color.BLACK));
        jLabel5.setBorder(new LineBorder(Color.BLACK));
        jLabel1.setBorder(new LineBorder(Color.BLACK));
        jLabel3.setBorder(new LineBorder(Color.BLACK));
        jButton1.setText("OK");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jPanel5.removeAll();
        jPanel6.removeAll();
    }

    public void handleJTextFiedlSetText() {
        ArrayList<Integer> list = new ArrayList<>();
        String[] s = jTextField1.getText().split(" ");
        for (int i = 0; i < s.length; i++) {
            if (s[i].equals("") == true) {
                continue;
            } else {

                list.add(Integer.parseInt(s[i]));
            }

        }
       

        ArrayList<ArrayList<Integer>> l = new Bai_5().bai_5(list);
        jTextField2.setText(l.get(0).size() + "");
        jTextField3.setText(l.get(0).size() + "");
        jPanel5.setLayout(new AbsoluteLayout());
        jPanel6.setLayout(new AbsoluteLayout());
        for (int i = 0; i < l.get(0).size(); i++) {
            JLabel temp = new JLabel();
            int W = 50;
            int H = 25;
            int X = 25;
            int Y = 5 * i + 25 * i;
            temp.setText(l.get(0).get(i) + "");
            temp.setBorder(new LineBorder(Color.white));
            jPanel5.add(temp, new AbsoluteConstraints(X, Y, W, H));
            jPanel5.updateUI();
        }
        for (int i = 0; i < l.get(1).size(); i++) {
            JLabel temp = new JLabel();
            int W = 50;
            int H = 25;
            int X = 25;
            int Y = 5 * i + 25 * i;
            temp.setText(l.get(1).get(i) + "");
            temp.setBorder(new LineBorder(Color.white));
            jPanel6.add(temp, new AbsoluteConstraints(X, Y, W, H));
            jPanel6.updateUI();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 312, 100, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 350));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 325, 50));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 325, 25));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 325, 350));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("jLabel5");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 325, 25));
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 164, 25));

        jLabel1.setText("jLabel1");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 164, 25));

        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 25, 160, 25));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 50, 160, 25));
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 164, 275));
        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 75, 160, 275));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 0, 325, 350));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 650, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
