/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_i.tuan34.tuan1;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import project_i.tuan29.Bai_4;

/**
 *
 * @author Admin
 */
public class Bai4 extends javax.swing.JPanel {

    /**
     * Creates new form
     */
    Bai_4 bai_4 = new Bai_4();

    public Bai4() {
        initComponents();
        setUp();
        jButton1.addActionListener((e) -> {
            jPanel5.removeAll();
            jPanel6.removeAll();
            handle();

        });

    }
  

    public void setUp() {

        jPanel5.removeAll();
        jPanel6.removeAll();
        jPanel5.updateUI();
        jPanel6.updateUI();
        
        jButton1.setText("OK");
        jLabel1.setText("số chia hết cho 3");
        jLabel1.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        jLabel2.setText("số chia hết cho 7");
        jLabel2.setHorizontalAlignment((int) CENTER_ALIGNMENT);

    }

    public void handle() {
        ArrayList<ArrayList<Integer>> list = bai_4.bai_4();
        int size3 = list.get(0).size();
        System.out.println("size3:" + size3);
        int size7 = list.get(1).size();
        System.out.println("size7:" + size7);
        int row = 11;
        int colum = 3;
        int X = 25, Y = 0;
        int WIDTH = 100, HEIGHT = 24;
        JLabel jL3[][] = new JLabel[row][colum];
        int count = 0;
        jPanel5.setLayout(new AbsoluteLayout());
        for (int i = 0; i < colum; i++) {

            for (int j = 0; j < row; j++) {
                jL3[j][i] = new JLabel();

                jL3[j][i].setText("" + list.get(0).get(count));
                count++;
                jL3[j][i].setHorizontalAlignment((int) CENTER_ALIGNMENT);
                jL3[j][i].setBorder(new LineBorder(Color.black));
                jPanel5.add(jL3[j][i], new AbsoluteConstraints(X, Y, WIDTH, HEIGHT));
                jPanel5.updateUI();
                Y = (3 * (j + 1) + (j + 1) * HEIGHT);
                if (count == size3) {
                    break;
                }
            }
            X = 25 + 25 * (i + 1) + (i + 1) * WIDTH;
            Y = 0;
        }
        int row1 = 10;
        int colum1 = 1;
        X = 75;
        Y = 0;
        WIDTH = 100;
        HEIGHT = 24;
        JLabel jL7[][] = new JLabel[row][colum];
        count = 0;
        jPanel6.setLayout(new AbsoluteLayout());
        for (int i = 0; i < colum1; i++) {

            for (int j = 0; j < row1; j++) {
                jL7[j][i] = new JLabel();

                jL7[j][i].setText("" + list.get(0).get(count));
                count++;
                jL7[j][i].setHorizontalAlignment((int) CENTER_ALIGNMENT);
                jL7[j][i].setBorder(new LineBorder(Color.black));
                jPanel6.add(jL7[j][i], new AbsoluteConstraints(X, Y, WIDTH, HEIGHT));
                jPanel6.updateUI();
                Y = (3 * (j + 1) + (j + 1) * HEIGHT);
                if (count == size3) {
                    break;
                }
            }
            X = 75 * (i + 1) + (i + 1) * WIDTH;
            Y = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 0));
        setMinimumSize(new java.awt.Dimension(750, 350));
        setPreferredSize(new java.awt.Dimension(750, 350));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 350));

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 325, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 350));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 400, 300));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 300));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 250, 350));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 650, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
