/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_i.tuan34.tuan1;

import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import project_i.tuan29.Bai_5;

/**
 *
 * @author Admin
 */
public class Bai5 extends javax.swing.JPanel {

    /**
     * Creates new form 
     */
    public Bai5() {
        initComponents();
        setUp();
        jButton1.addActionListener((e) -> {
            jPanel3.removeAll();
            handle();
            jPanel3.updateUI();
        });
        
    }

    public void setUp() {
        jLabel1.setText("vị trí bắt đầu");
        jLabel2.setText("vị trí kết thúc");
        jTextField1.setText("1000");
        jTextField2.setText("2000");
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jButton1.setText("OK");
        jPanel3.removeAll();
        jPanel3.updateUI();
        
    }

    public void handle() {
        Map<Integer, Integer> list = new HashMap<Integer, Integer>();
                 list = new Bai_5().bai_5();
        int size = list.size();
        System.out.println("size:" + size);
        int row = 3;
        int colum = 3;
        int X = 1, Y = 1;
        int WIDTH = 100, HEIGHT = 55;
        JLabel jL3[][] = new JLabel[row][colum];
        int count = 0;
        jPanel3.setLayout(new AbsoluteLayout());
        Set set = list.entrySet();
        Iterator itr = set.iterator();
       
        for (int i = 0; i < colum; i++) {

            for (int j = 0; j < row; j++) {
                itr.hasNext();
                Map.Entry entry = (Map.Entry) itr.next();
                jL3[j][i] = new JLabel();

                jL3[j][i].setText("" + entry.getValue());
                count++;
                jL3[j][i].setHorizontalAlignment((int) CENTER_ALIGNMENT);
                jL3[j][i].setBorder(new LineBorder(Color.yellow));
                jPanel3.add(jL3[j][i], new AbsoluteConstraints(X, Y, WIDTH, HEIGHT));
                Y = 1 + (3 * (j + 1) + (j + 1) * HEIGHT);
                if (count == size) {
                    break;
                }
            }
            X = 1 + 10 * (i + 1) + (i + 1) * WIDTH;
            Y = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 325, 100, 25));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 25));

        jTextField1.setText("jTextField1");
        jTextField1.setActionCommand("<Not Set>");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 100, 25));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 100, 25));

        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 100, 25));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 350));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 87, 324, 174));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 650, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
