/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project__i.tuan34;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

import project__i.tuan34.tuan1.Tuan29;
import project__i.tuan34.tuan2.Tuan30;
import project__i.tuan34.tuan3.Tuan31;
import project__i.tuan34.tuan4.Tuan32;
import project__i.tuan33.GUI;

/**
 *
 * @author Admin
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    CardLayout cardLayout = new CardLayout();

    public Interface() {

        initComponents();
        setUp();
        getExWeek();
        Action();

    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setUp() {
        setTitle("Tổng hợp bài tập tuần --- Vũ Trọng Quảng --- 20198256");
        setSize(865, 485);
        tuan1.setText("Tuần 29");
        tuan2.setText("Tuần 30");
        tuan3.setText("Tuần 31");
        tuan4.setText("Tuần 32");
        tuan5.setText("Tuần 33");
       
    }

    public void changeColor(String str) {
        Color color = new Color(255, 153, 153);
        Color c = new Color(76, 80, 82);
        if (str.equals("tuan29")) {
            tuan1.setBackground(color);
            tuan2.setBackground(c);
            tuan3.setBackground(c);
            tuan4.setBackground(c);
            tuan5.setBackground(c);
        } else if (str.equals("tuan30")) {
            tuan2.setBackground(color);
            tuan1.setBackground(c);
            tuan3.setBackground(c);
            tuan4.setBackground(c);
            tuan5.setBackground(c);
        } else if (str.equals("tuan31")) {
            tuan3.setBackground(color);
            tuan1.setBackground(c);
            tuan2.setBackground(c);
            tuan4.setBackground(c);
            tuan5.setBackground(c);
        } else if (str.equals("tuan32")) {
            tuan4.setBackground(color);
            tuan1.setBackground(c);
            tuan2.setBackground(c);
            tuan3.setBackground(c);
            tuan5.setBackground(c);
        } else if (str.equals("tuan33")) {
            tuan5.setBackground(color);
            tuan1.setBackground(c);
            tuan2.setBackground(c);
            tuan3.setBackground(c);
            tuan4.setBackground(c);
        }
        jPanel1.updateUI();
    }

    public void getExWeek() {
        cardLayout = (CardLayout) (jPanel3.getLayout());
        jPanel3.setLayout(cardLayout);

        jPanel3.add(new Tuan29(), "tuan29");
        jPanel3.add(new Tuan30(), "tuan30");
        jPanel3.add(new Tuan31(), "tuan31");
        jPanel3.add(new Tuan32(), "tuan32");
        cardLayout.show(jPanel3, "tuan29");

    }

    public void Action() {
        tuan1.addActionListener((e) -> {
            setTitle("Tổng hợp bài tập tuần --- Vũ Trọng Quảng --- 20198256 --- tuan 29");
            changeColor("tuan29");
            cardLayout.show(jPanel3, "tuan29");

        });
        tuan2.addActionListener((e) -> {
            setTitle("Tổng hợp bài tập tuần --- Vũ Trọng Quảng --- 20198256 --- tuan 30");
            changeColor("tuan30");
            cardLayout.show(jPanel3, "tuan30");
        });
        tuan3.addActionListener((e) -> {
            setTitle("Tổng hợp bài tập tuần --- Vũ Trọng Quảng --- 20198256 --- tuan 31");
            changeColor("tuan31");
            cardLayout.show(jPanel3, "tuan31");
        });
        tuan4.addActionListener((e) -> {
            setTitle("Tổng hợp bài tập tuần --- Vũ Trọng Quảng --- 20198256 --- tuan 32");
            changeColor("tuan32");
            cardLayout.show(jPanel3, "tuan32");
        });
        tuan5.addActionListener((e) -> {
            changeColor("tuan33");
            new GUI().setVisible(true);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tuan1 = new javax.swing.JButton();
        tuan2 = new javax.swing.JButton();
        tuan3 = new javax.swing.JButton();
        tuan4 = new javax.swing.JButton();
        tuan5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        tuan1.setText("jButton1");
        jPanel2.add(tuan1);
        tuan1.setBounds(0, 0, 170, 50);

        tuan2.setText("jButton2");
        jPanel2.add(tuan2);
        tuan2.setBounds(170, 0, 170, 50);

        tuan3.setText("jButton3");
        jPanel2.add(tuan3);
        tuan3.setBounds(340, 0, 170, 50);

        tuan4.setText("jButton4");
        jPanel2.add(tuan4);
        tuan4.setBounds(510, 0, 170, 50);

        tuan5.setText("jButton5");
        jPanel2.add(tuan5);
        tuan5.setBounds(680, 0, 170, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 850, 50);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 50, 850, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton tuan1;
    private javax.swing.JButton tuan2;
    private javax.swing.JButton tuan3;
    private javax.swing.JButton tuan4;
    private javax.swing.JButton tuan5;
    // End of variables declaration//GEN-END:variables
}
